### ISSUE TITLE
Using seeds produces empty files in the seed dir

### ISSUE THREAD

**Issue by Nintorac** [starburstdata/dbt-trino#226]
### Expected behavior

I created a project with some seeds and materialized tables, I then can use the pyarrow library to load the tables.

### Actual behavior

For any of the materialised tables there is no issue and the tables are loaded as expected. However for tables that are the result of seeds there is an error as pyarrow tries to load the directory as a file. When listing the dir you can see two files in it where there should only be one.

Another behavior I have noted that may be related is that when rerunning the seed function results in an error because a file cannot be overwritten though I have not confirmed this hunch.

### Steps To Reproduce

Given this docker compose

```yaml
version: '3.7'
services:


  trino-coordinator:
    image: 'trinodb/trino:392'
    hostname: trino-coordinator
    user: trino:trino
    ports:
      - '8080:8080'
    volumes:
      - ./infra/trino/etc:/etc/trino
      - ./trino-cli-392-executable.jar:/trino
    tmpfs:
      - /spill:rw
    networks:
      - midi-etl
    restart: on-failure
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 15G

  mariadb:
    image: 'mariadb:latest'
    hostname: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    volumes:
      - mariadb-data:/var/lib/mysql/
    networks:
      - midi-etl

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./infra/hive/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - midi-etl

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-reddit-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - midi-etl

volumes:
  minio-reddit-data:
    driver: local
  mariadb-data:
    driver: local
  spill:
    driver: local
  
networks:
  midi-etl:
    driver: bridge

```

create a dbt project with a seed file, deploy the seeds and then try to run the following

```python
from pyarrow import parquet as pq
import pandas as pd
import pyarrow.dataset as ds
import s3fs

#%%
endpoint_url ='http://localhost:9000'
aws_access_key_id ='minio'
aws_secret_access_key ='minio123'
fs = s3fs.S3FileSystem(
        anon=False,
        use_ssl=False,
        client_kwargs={
            "region_name": "us-east-1",
            "endpoint_url": endpoint_url,
            "aws_access_key_id": aws_access_key_id,
            "aws_secret_access_key": aws_secret_access_key,
            "verify": False,
        }
    ) 
pq.read_table('path/to/seeds', filesystem=fs)
```

then observe that there are two files when listing the seed dir
```
>>> fs.listdir("path/to/seeds")
[{'Key': 'path/to/seeds/',
  'LastModified': datetime.datetime(2023, 2, 5, 7, 43, 49, 822000, tzinfo=tzutc()),
  'ETag': '"d41d8cd98f00b204e9800998ecf8427e"',
  'Size': 0,
  'StorageClass': 'STANDARD',
  'Owner': {'DisplayName': 'minio',
   'ID': '02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4'},
  'type': 'file',
  'size': 0,
  'name': 'path/to/seeds/'},
 {'Key': 'path/to/seeds/20230205_074350_00008_9aq5u_01fdb7ec-57c5-4b22-88e5-c84ee87b83a9',
  'LastModified': datetime.datetime(2023, 2, 5, 7, 43, 51, 756000, tzinfo=tzutc()),
  'ETag': '"855ed46e79733e1293349ec2ca583a5b"',
  'Size': 1773,
  'StorageClass': 'STANDARD',
  'Owner': {'DisplayName': 'minio',
   'ID': '02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4'},
  'type': 'file',
  'size': 1773,
  'name': 'path/to/seeds/20230205_074350_00008_9aq5u_01fdb7ec-57c5-4b22-88e5-c84ee87b83a9'}]
```
doing the same thing on a materialised table there is only a single entry

```
>>> fs.listdir("path/to/some_model")
[{'Key': 'path/to/some_model/20230205_074350_00008_9aq5u_01fdb7ec-57c5-4b22-88e5-c84ee87b83a9',
  'LastModified': datetime.datetime(2023, 2, 5, 7, 43, 51, 756000, tzinfo=tzutc()),
  'ETag': '"855ed46e79733e1293349ec2ca583a5b"',
  'Size': 1773,
  'StorageClass': 'STANDARD',
  'Owner': {'DisplayName': 'minio',
   'ID': '02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4'},
  'type': 'file',
  'size': 1773,
  'name': 'path/to/seeds/20230205_074350_00008_9aq5u_01fdb7ec-57c5-4b22-88e5-c84ee87b83a9'}]
```

### Log output/Screenshots

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/home/athena/nintorac/lakh_dataset/midi_etl_notebooks/basic_analysis.py in line 2
      [51](file:///home/athena/nintorac/lakh_dataset/midi_etl_notebooks/basic_analysis.py?line=50) #%%
----> [52](file:///home/athena/nintorac/lakh_dataset/midi_etl_notebooks/basic_analysis.py?line=51) program_information = ds.dataset(
      [53](file:///home/athena/nintorac/lakh_dataset/midi_etl_notebooks/basic_analysis.py?line=52)     'midietl/midi_standard/program_information',
      [54](file:///home/athena/nintorac/lakh_dataset/midi_etl_notebooks/basic_analysis.py?line=53)     filesystem=fs
      [55](file:///home/athena/nintorac/lakh_dataset/midi_etl_notebooks/basic_analysis.py?line=54) ).to_table()
      [56](file:///home/athena/nintorac/lakh_dataset/midi_etl_notebooks/basic_analysis.py?line=55) conn.query("select * from program_information limit 10").to_df()

File ~/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py:762, in dataset(source, schema, format, filesystem, partitioning, partition_base_dir, exclude_invalid_files, ignore_prefixes)
    [751](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=750) kwargs = dict(
    [752](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=751)     schema=schema,
    [753](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=752)     filesystem=filesystem,
   (...)
    [758](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=757)     selector_ignore_prefixes=ignore_prefixes
    [759](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=758) )
    [761](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=760) if _is_path_like(source):
--> [762](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=761)     return _filesystem_dataset(source, **kwargs)
    [763](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=762) elif isinstance(source, (tuple, list)):
    [764](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=763)     if all(_is_path_like(elem) for elem in source):

File ~/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py:455, in _filesystem_dataset(source, schema, filesystem, partitioning, format, partition_base_dir, exclude_invalid_files, selector_ignore_prefixes)
    [447](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=446) options = FileSystemFactoryOptions(
    [448](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=447)     partitioning=partitioning,
    [449](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=448)     partition_base_dir=partition_base_dir,
    [450](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=449)     exclude_invalid_files=exclude_invalid_files,
    [451](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=450)     selector_ignore_prefixes=selector_ignore_prefixes
    [452](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=451) )
    [453](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=452) factory = FileSystemDatasetFactory(fs, paths_or_selector, format, options)
--> [455](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/dataset.py?line=454) return factory.finish(schema)

File ~/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/_dataset.pyx:2062, in pyarrow._dataset.DatasetFactory.finish()

File ~/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/error.pxi:144, in pyarrow.lib.pyarrow_internal_check_status()

File ~/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/_fs.pyx:1551, in pyarrow._fs._cb_open_input_file()

File ~/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/fs.py:422, in FSSpecHandler.open_input_file(self, path)
    [419](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/fs.py?line=418) from pyarrow import PythonFile
    [421](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/fs.py?line=420) if not self.fs.isfile(path):
--> [422](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/fs.py?line=421)     raise FileNotFoundError(path)
    [424](file:///home/athena/miniconda3/envs/lakh_midi/lib/python3.10/site-packages/pyarrow/fs.py?line=423) return PythonFile(self.fs.open(path, mode="rb"), mode="r")

FileNotFoundError: midietl/midi_standard/program_information/
```

### Operating System

Fedora 36 Workstation

### dbt version

1.3.1

### Trino Server version

392

### Python version

Python 3.10.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
