### ISSUE TITLE
oauth authentication not working in dbt Core

### ISSUE THREAD

**Issue by dataders** [starburstdata/dbt-trino#275]
### Expected behavior

Following the below guidance from https://github.com/dbt-labs/docs.getdbt.com/pull/3055#discussion_r1150457445
> To use OAuth in dbt-trino you can simply add method: oauth to the profiles.yml. During first authentication, it automatically opens a browser with OAuth provider to authenticate.

I did so, and I don't get a browser pop-up. I'm not sure how to debug..

when I run `dbt run` or `dbt debug` nothing happens for minutes then fails with the below error:

```python
HTTPSConnectionPool(
  host='bunbundersders.trino.galaxy-dev.io', port=433):
    Max retries exceeded with url: /v1/statement (
     Caused by ConnectTimeoutError(
       <urllib3.connection.HTTPSConnection object at 0x107b4eb00>,
         'Connection to bunbundersders.trino.galaxy-dev.io timed out. (connect timeout=30.0)'))
```

#### `profiles.yml`

```yaml
sandbox-galaxy:
  target: oauth
  outputs:
    oauth:
      type: trino
      method: oauth
      host: bunbundersders.trino.galaxy-dev.io
      catalog: dbt_target
      schema: dataders
      port: 433
```

### Actual behavior

a

### Steps To Reproduce

a

### Log output/Screenshots

a

### Operating System

macos

### dbt version

1.4.1

### Trino Server version

Galaxy?

### Python version

3.10.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
