### ISSUE TITLE
Error when disable retries (set retries = 0) in profiles.yml

### ISSUE THREAD

**Issue by quannh-uet** [starburstdata/dbt-trino#310]
### Expected behavior
When dbt run model failed, I don't want re-run this model again (I use Airflow for retries latter).
So I disable retries when dbt run fail following [this document](https://docs.getdbt.com/docs/core/connect-data-platform/trino-setup#additional-parameters)

So I set this parameters `retries: 0` in my dbt `profiles.yml` config

### Actual behavior

I getting error when compile dbt project.

### Steps To Reproduce

Config `profiles.yml` following:

```
trino:
  target: dev
  outputs:
    dev:
      type: trino
      method: ldap 
      user: "{{ env_var('DBT_TRINO_USER') }}"
      password: "{{ env_var('DBT_TRINO_PASSWORD') }}"
      host: "{{ env_var('DBT_TRINO_HOST') }}"
      port: "{{ env_var('DBT_TRINO_PORT') }}"
      catalog: "{{ env_var('DBT_TRINO_CATALOG') }}"
      schema: "{{ env_var('DBT_TRINO_SCHEMA') }}"
      threads: 2
      retries: 0
      http_scheme: https
      timezone: UTC
```

Run `dbt compile` command
```
$ dbt compile
09:01:09  Running with dbt=1.5.0
09:01:09  Unable to do partial parsing because profile has changed
09:01:15  Found 506 models, 40 tests, 0 snapshots, 0 analyses, 447 macros, 0 operations, 0 seed files, 298 sources, 0 exposures, 0 metrics, 0 groups
09:01:15  
09:01:15  Encountered an error:
Runtime Error
  local variable 'attempt' referenced before assignment
```

### Operating System

Linux

### dbt version

1.5.0

### Trino Server version

403

### Python version

Python 3.9.11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
