### ISSUE TITLE
Add support for DECIMAL, REAL, DOUBLE, TIME in dbt seed

### ISSUE THREAD

**Issue by findinpath** [starburstdata/dbt-trino#46]
`dbt seed` command does not currently escape some data types supported by trino.

Perform the changes in the method `dbt.adapters.trino.connections.ConnectionWrapper._escape_value`

Make sure to add a corresponding model which contains all these types in the automated tests.

```
seeds: 
  jaffle_shop:
    seed_data_types:
      +column_types:
        c_timestamp: timestamp
        c_date: date
        c_time: time
        c_char: char(10)
        short_decimal: decimal(10,2)
        long_decimal: decimal(10,2)
        c_real: real
        c_float: float
```

Check https://docs.getdbt.com/docs/building-a-dbt-project/seeds  (the FAQ section as well) to get a better understanding of seeds in dbt. Do perform also tests for the seeds (as documented in the " How do I test and document seeds?" from the FAQ section) to ensure compatibility with the functionality provided by dbt.
